name: Datagen
favicon: null
layout_spectrum: 0.7688650984782726
typography_spectrum: 0.5911689384374768
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7543067736551166
  lightness: 0.24533605226315558
  saturation: 0.5220454791560769
  rhythmicContrast: 0.33495420194230974
purpose: []
